/* This file is generated by src/lib/generate-blog-index.mjs — do not edit. */
import bp_blogpost_3 from './blogpost_3.md';
import bp_blogpost_2 from './blogpost_2.md';
import bp_blogpost_1 from './blogpost_1.md';

const posts: Record<string, string> = {
  "blogpost-3": bp_blogpost_3,
  "blogpost-2": bp_blogpost_2,
  "blogpost-1": bp_blogpost_1,
};

export default posts;
